version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pvz_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shwisdtt345345
      POSTGRES_DB: pvz_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pvz_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:shwisdtt345345@db:5432/pvz_db
    command: >
      uvicorn src.main:app
      --host 0.0.0.0
      --port 8000

volumes:
  pg_data: