"""init

Revision ID: 0001
Revises: 
Create Date: 2026-04-21 18:46:06.076703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvzs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.Enum('MOSCOW', 'SPB', 'KAZAN', name='allowedcities'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvzs_created_at'), 'pvzs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MODERATOR', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('receptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'CLOSE', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pvz_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pvz_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptions_created_at'), 'receptions', ['created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ELECTRONICS', 'CLOTHING', 'FOOTWEAR', name='producttype'), nullable=False),
    sa.Column('reception_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reception_id'], ['receptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index(op.f('ix_receptions_created_at'), table_name='receptions')
    op.drop_table('receptions')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pvzs_created_at'), table_name='pvzs')
    op.drop_table('pvzs')
    # ### end Alembic commands ###
