"""pvz_id change foreighn_key

Revision ID: 0002
Revises: 
Create Date: 2026-04-24 17:53:25.616405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('receptions_pvz_id_fkey'), 'receptions', type_='foreignkey')
    op.create_foreign_key(None, 'receptions', 'pvzs', ['pvz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receptions', type_='foreignkey')
    op.create_foreign_key(op.f('receptions_pvz_id_fkey'), 'receptions', 'users', ['pvz_id'], ['id'])
    # ### end Alembic commands ###
